version: '3.7'

services:
  syntaxflavor_db:
    image: postgres:latest
    container_name: syntaxflavor_db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./env/postgres.env

  syntaxflavor_backend:
    build: .
    container_name: syntaxflavor_backend
    ports:
      - '8000:8000'
    depends_on:
      - syntaxflavor_db
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  syntaxflavor_keycloak:
    image: quay.io/keycloak/keycloak
    container_name: syntaxflavor_keycloak
    ports:
      - '8082:8080'
    env_file:
      - ./env/keycloak.env
    volumes:
      - ./src/main/resources/imports/keycloak-realm:/opt/keycloak/data/import
    depends_on:
      - syntaxflavor_db
    command: ["start-dev", "--import-realm"]
    restart: always
    