version: '3.7'

services:
  syntaxflavor_db:
    image: postgres:latest
    container_name: syntaxflavor_db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./env/postgres.env

  syntaxflavor_backend:
    build: .
    container_name: syntaxflavor_backend
    ports:
      - '8080:8080'
    depends_on:
      - syntaxflavor_db
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  minio:
    image: minio/minio:latest
    container_name: syntaxflavor_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
    env_file:
      - ./env/minio.env
    command: server /data --console-address ":9001"

