version: '3.7'

services:
  syntaxflavor_db:
    image: postgres:latest
    container_name: syntaxflavor_db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./env/postgres.env

  syntaxflavor_backend:
    build:
      context: .
      dockerfile: Dockerfile.mac
    container_name: syntaxflavor_backend
    ports:
      - '8000:8000'
    depends_on:
      - syntaxflavor_db
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
