spring:
  application:
    name: syntax_flavor_backend
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://syntaxflavor_db:5432/syntaxflavor
    username: postgres
    password: 123456 # Consider using environment variables for sensitive data
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  minio:
    url: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: syntaxflavorbucket
  mail:
    host: mailhog
    port: 1025
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  keycloak:
    auth-server-url: http://syntaxflavor_keycloak:8080
    realm: syntaxflavor_users
    resource: syntaxflavor
    public-client: false
    ssl-required: external
    bearer-only: false
    credentials:
      secret: NmuoI18AX2WNcXwnWmScVGUdjC7gMFvr # Use environment variables for sensitive data
    admin:
      username: admin
      password: admin
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.keycloak: DEBUG
    org.springframework.web: TRACE
    bo.edu.ucb: TRACE
server:
  port: 8080
