spring:
    application:
        name: syntax_flavor_backend
    config:
        activate:
            on-profile: default
    datasource:
        url: jdbc:postgresql://localhost:5432/syntaxflavor
        username: postgres
        password: 123456 # TODO: Change this password set from .env file
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8080


---

spring:
    application:
        name: syntax_flavor_backend
    config:
        activate:
            on-profile: docker
    datasource:
        url: jdbc:postgresql://syntaxflavor_db:5432/syntaxflavor
        username: postgres
        password: 123456 # TODO: Change this password set from .env file
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        
server:
    port: 8080

---
keycloak:
  auth-server-url: http://localhost:8082/realms/syntaxflavor_users
  realm: syntaxflavor_users
  resource: syntaxflavor # El nombre del cliente que creaste en Keycloak
  public-client: true
  ssl-required: external
  bearer-only: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/syntaxflavor_users


