### obtener información del comensal por id #####
GET http://localhost:8080/api/v1/user/customer/profile
Accept: application/json
customerId: 1

### actualizar información de facturación del comensal #####
PATCH http://localhost:8080/api/v1/user/customer
Content-Type: application/json

{
  "customerId": 1,
  "billName": "MonteroUpdated",
  "nit":"12334135"
}

### crear comensal #####
POST http://localhost:8080/api/v1/public/signup?type=customer
Content-Type: application/json
Accept: application/json

{
    "name": "customer111",
    "email": "customer111@example.com",
    "password": "123456789",
    "nit": "987654321",
    "billName": "ExampleBillName"
}
