##FIXME: separar el endpoint de creación de cuentas de cocina con el de customers
POST http://localhost:8080/api/v1/public/signup?type=kitchen
Content-Type: application/json
Accept: application/json

{
    "name": "kitchen1",
    "email": "kitchen12@example.com",
    "password": "123456",
    "location": "ExampleLocation"
}