# GET /api/v1/menu/item
### trata de dejar este test con <JWT_TOKEN> debes copiar el access_token
GET http://localhost:8080/api/v1/menu/item/all
Authorization: Bearer <JWT_TOKEN>
Accept: application/json


###
GET http://localhost:8080/api/v1/menu/item?minPrice=10&maxPrice=20&pageNumber=0&pageSize=20&sortAscending=false
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

###
GET http://localhost:8080/api/v1/menu/item/1/image

### 
PATCH https://localhost:8080/api/v1/public/menu/item/1/image
Content-Type: multipart/form-data boundary="------uploadImageLimiter"

------uploadImageLimiter
Content-Disposition: form-data; name="text"

title
------uploadImageLimiter
Content-Disposition: form-data; name="file"; filename="photo1.png"
Content-Type: image/png

< ./resources/photo1.png
------uploadImageLimiter--
