### Listar todas las órdenes por parametros: fecha minima, fecha maxima, estado, paginación y ordenamiento
### status: Pendiente, Entregado, Cancelado
GET http://localhost:8080/api/v1/order?status=Pendiente&minDate=2024-09-29T04:05:00&maxDate=2024-10-20T23:59:59&pageNumber=1&pageSize=20&sortAscending=true
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

###
GET http://localhost:8080/api/v1/order/status?status=Cancelado&pageNumber=0
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

### Post para crear una ORDEN con JWT token (requiere autenticación)
### tambien puede enviarse el paramtro "null" sin comillas
POST http://localhost:8080/api/v1/order
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json
Accept: application/json

{
  "tableCode":"123-234-123",
  "itemIdQuantityMap": {
    "1": 2,
    "2": 1
  }
}

### Actualizar una orden (cambiar estado a Cancelado)
PUT http://localhost:8080/api/v1/order/cancel?orderId=834
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

### Actualizar una orden (cambiar estado a Entregado)
PUT http://localhost:8080/api/v1/order/deliver?orderId=872
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

### Listar órdenes del cliente (extraído del token JWT)
### FIXME: El endpoint no esta funciona solo en casos muy específicos (id=1002)
GET http://localhost:8080/api/v1/order/customer?status=Entregado&pageNumber=0&pageSize=10&sortAscending=false
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

### Listar órdenes del cliente (extraído del token JWT)
GET http://localhost:8080/api/v1/order/customer
Authorization: Bearer <JWT_TOKEN>
Accept: application/json

###

#### Post para crear una ORDEN pública (sin autenticación)
#POST http://localhost:8080/api/v1/public/order
#Content-Type: application/json
#Accept: application/json
#
#{
#  "customerId": 1,
#  "itemIdQuantityMap": {
#    "1": 2,
#    "2": 1
#  }
#}