#### login user esto te da el access_token
POST http://localhost:8080/api/v1/public/login
Content-Type: application/json
Accept: application/json

{
    "email": "customerTest@example.com",
    "password": "123456"
}
// FIXME: manejar el error de cuenta no verificada
// TODO: Documentar todos los endpoints de la API

### Test List Users with Kitchen
GET http://localhost:8080/api/v1/users-with-kitchen?page=0&size=5&sortBy=id&sortOrder=desc
Authorization: Bearer <JWT_TOKEN>
Accept: application/json


### signup user customer

POST http://146.190.141.101:8080/api/v1/public/signup?type=customer
Content-Type: application/json
Accept: application/json

{
    "name": "customerExample2",
    "email": "customerTest2@example.com",
    "password": "123456",
    "nit": "987654321",
    "billName": "ExampleBillName"
}

### sign up user kitchen
POST http://146.190.141.101:8080/api/v1/public/signup?type=kitchen
Content-Type: application/json
Accept: application/json

{
    "name": "kitchen1Test",
    "email": "kitchen1Test@example.com",
    "password": "123456",
    "location": "ExampleLocation"
}
### signup user administrator
POST http://146.190.141.101:8080/api/v1/public/signup?type=administrator
Content-Type: application/json
Accept: application/json

{
    "name": "administratorTest",
    "email": "administratorTest@example.com",
    "password": "123456"
}