
##### sign up user
POST http://localhost:8080/api/v1/public/user
Content-Type: application/json
Accept: application/json

{
    "name": "example1234",
    "email": "example1234@example.com",
    "password": "123456789"
}

#### login user
POST http://localhost:8080/api/v1/public/login
Content-Type: application/json
Accept: application/json

{
    "email": "example1234@example.com",
    "password": "123456789"
}