insert into kitchens (location, users_id) values ('Shangfang', 1001);
insert into kitchens (location, users_id) values ('Novaya Igirma', 1002);
insert into kitchens (location, users_id) values ('Weiyang', 1003);
insert into kitchens (location, users_id) values ('Qianjin', 1004);
insert into kitchens (location, users_id) values ('Nikolayevka', 1005);
insert into kitchens (location, users_id) values ('Curahkalak Tengah', 1006);
insert into kitchens (location, users_id) values ('Figueira dos Cavaleiros', 1007);
insert into kitchens (location, users_id) values ('Vannes', 1008);
insert into kitchens (location, users_id) values ('Jesus Maria', 1009);
insert into kitchens (location, users_id) values ('Gorki', 1010);
insert into kitchens (location, users_id) values ('Lumbayan', 1011);
insert into kitchens (location, users_id) values ('La Montanita', 1012);
insert into kitchens (location, users_id) values ('Bayanan', 1013);
insert into kitchens (location, users_id) values ('Juan Santiago', 1014);
insert into kitchens (location, users_id) values ('Toba', 1015);
insert into kitchens (location, users_id) values ('Naranjal', 1016);
insert into kitchens (location, users_id) values ('Ano Kopanakion', 1017);
insert into kitchens (location, users_id) values ('Pakusari', 1018);
insert into kitchens (location, users_id) values ('Burewala', 1019);
insert into kitchens (location, users_id) values ('Vykhino-Zhulebino', 1020);
insert into kitchens (location, users_id) values ('Morales', 1021);
insert into kitchens (location, users_id) values ('Tanggu', 1022);
insert into kitchens (location, users_id) values ('Darenzhuang', 1023);
insert into kitchens (location, users_id) values ('San Lucas Sacatepequez', 1024);
insert into kitchens (location, users_id) values ('Norfolk County', 1025);
insert into kitchens (location, users_id) values ('Wagini', 1026);
insert into kitchens (location, users_id) values ('Chelgard', 1027);
insert into kitchens (location, users_id) values ('Dalazi', 1028);
insert into kitchens (location, users_id) values ('Meicheng', 1029);
insert into kitchens (location, users_id) values ('Jeponkrajan', 1030);
insert into kitchens (location, users_id) values ('Canutama', 1031);
insert into kitchens (location, users_id) values ('Laojieji', 1032);
insert into kitchens (location, users_id) values ('Gori', 1033);
insert into kitchens (location, users_id) values ('Krasnaye', 1034);
insert into kitchens (location, users_id) values ('Nong Yai', 1035);
insert into kitchens (location, users_id) values ('Chambly', 1036);
insert into kitchens (location, users_id) values ('Siruma', 1037);
insert into kitchens (location, users_id) values ('Hejia', 1038);
insert into kitchens (location, users_id) values ('Hongqi', 1039);
insert into kitchens (location, users_id) values ('Ermelo', 1040);
insert into kitchens (location, users_id) values ('Napanee Downtown', 1041);
insert into kitchens (location, users_id) values ('Oemollo', 1042);
insert into kitchens (location, users_id) values ('Rusan', 1043);
insert into kitchens (location, users_id) values ('Riyue', 1044);
insert into kitchens (location, users_id) values ('Zeya', 1045);
insert into kitchens (location, users_id) values ('Karangmelok', 1046);
insert into kitchens (location, users_id) values ('Daqiao', 1047);
insert into kitchens (location, users_id) values ('Cordeiro', 1048);
insert into kitchens (location, users_id) values ('Mijiang', 1049);
insert into kitchens (location, users_id) values ('Joconal', 1050);
insert into kitchens (location, users_id) values ('Dongshan', 1051);
insert into kitchens (location, users_id) values ('Papa', 1052);
insert into kitchens (location, users_id) values ('Corumba', 1053);
insert into kitchens (location, users_id) values ('Verkhozim', 1054);
insert into kitchens (location, users_id) values ('Ibaraki', 1055);
insert into kitchens (location, users_id) values ('Pingwang', 1056);
insert into kitchens (location, users_id) values ('Mora', 1057);
insert into kitchens (location, users_id) values ('Askainen', 1058);
insert into kitchens (location, users_id) values ('Jati', 1059);
insert into kitchens (location, users_id) values ('Inderka', 1060);
insert into kitchens (location, users_id) values ('Krushevo', 1061);
insert into kitchens (location, users_id) values ('Mangge', 1062);
insert into kitchens (location, users_id) values ('Ubatuba', 1063);
insert into kitchens (location, users_id) values ('Altunemil', 1064);
insert into kitchens (location, users_id) values ('Altay', 1065);
insert into kitchens (location, users_id) values ('Yandev', 1066);
insert into kitchens (location, users_id) values ('Dingzigu', 1067);
insert into kitchens (location, users_id) values ('Doghs', 1068);
insert into kitchens (location, users_id) values ('Divisoria', 1069);
insert into kitchens (location, users_id) values ('Tayabo', 1070);
insert into kitchens (location, users_id) values ('Calangain', 1071);
insert into kitchens (location, users_id) values ('Rio das Ostras', 1072);
insert into kitchens (location, users_id) values ('Ouro Preto', 1073);
insert into kitchens (location, users_id) values ('Ning\'er', 1074);
insert into kitchens (location, users_id) values ('Brodnica', 1075);
insert into kitchens (location, users_id) values ('Chalons-en-Champagne', 1076);
insert into kitchens (location, users_id) values ('Zhishan', 1077);
insert into kitchens (location, users_id) values ('Vu Thu', 1078);
insert into kitchens (location, users_id) values ('Taoyao', 1079);
insert into kitchens (location, users_id) values ('Gaokan', 1080);
insert into kitchens (location, users_id) values ('Tucson', 1081);
insert into kitchens (location, users_id) values ('Voiron', 1082);
insert into kitchens (location, users_id) values ('Tangwang', 1083);
insert into kitchens (location, users_id) values ('Dobri Dol', 1084);
insert into kitchens (location, users_id) values ('Monguno', 1085);
insert into kitchens (location, users_id) values ('Soito', 1086);
insert into kitchens (location, users_id) values ('Pindi Bhattian', 1087);
insert into kitchens (location, users_id) values ('Kishi', 1088);
insert into kitchens (location, users_id) values ('Gorno-Altaysk', 1089);
insert into kitchens (location, users_id) values ('Suran', 1090);
insert into kitchens (location, users_id) values ('San Juan', 1091);
insert into kitchens (location, users_id) values ('Balao', 1092);
insert into kitchens (location, users_id) values ('Little Current', 1093);
insert into kitchens (location, users_id) values ('Arias', 1094);
insert into kitchens (location, users_id) values ('Las Vegas', 1095);
insert into kitchens (location, users_id) values ('Jiaodai', 1096);
insert into kitchens (location, users_id) values ('Xinbao', 1097);
insert into kitchens (location, users_id) values ('Vancouver', 1098);
insert into kitchens (location, users_id) values ('Tangnanzhen', 1099);
insert into kitchens (location, users_id) values ('Al Awja', 1100);
