insert into users (name, email, password) values ('Shangfang', 'Shangfang@syntax.flavor', 'Shangfang');
insert into users (name, email, password) values ('Novaya Igirma', 'NovayaIgirma@syntax.flavor', 'NovayaIgirma');
insert into users (name, email, password) values ('Weiyang', 'Weiyang@syntax.flavor', 'Weiyang');
insert into users (name, email, password) values ('Qianjin', 'Qianjin@syntax.flavor', 'Qianjin');
insert into users (name, email, password) values ('Nikolayevka', 'Nikolayevka@syntax.flavor', 'Nikolayevka');
insert into users (name, email, password) values ('Curahkalak Tengah', 'CurahkalakTengah@syntax.flavor', 'CurahkalakTengah');
insert into users (name, email, password) values ('Figueira dos Cavaleiros', 'FigueiradosCavaleiros@syntax.flavor', 'FigueiradosCavaleiros');
insert into users (name, email, password) values ('Vannes', 'Vannes@syntax.flavor', 'Vannes');
insert into users (name, email, password) values ('Jesús María', 'JesusMaria@syntax.flavor', 'JesusMaria');
insert into users (name, email, password) values ('Górki', 'Gorki@syntax.flavor', 'Gorki');
insert into users (name, email, password) values ('Lumbayan', 'Lumbayan@syntax.flavor', 'Lumbayan');
insert into users (name, email, password) values ('La Montañita', 'LaMontanita@syntax.flavor', 'LaMontanita');
insert into users (name, email, password) values ('Bayanan', 'Bayanan@syntax.flavor', 'Bayanan');
insert into users (name, email, password) values ('Juan Santiago', 'JuanSantiago@syntax.flavor', 'JuanSantiago');
insert into users (name, email, password) values ('Toba', 'Toba@syntax.flavor', 'Toba');
insert into users (name, email, password) values ('Naranjal', 'Naranjal@syntax.flavor', 'Naranjal');
insert into users (name, email, password) values ('Áno Kopanákion', 'AnoKopanakion@syntax.flavor', 'AnoKopanakion');
insert into users (name, email, password) values ('Pakusari', 'Pakusari@syntax.flavor', 'Pakusari');
insert into users (name, email, password) values ('Būrewāla', 'Burewala@syntax.flavor', 'Burewala');
insert into users (name, email, password) values ('Vykhino-Zhulebino', 'VykhinoZhulebino@syntax.flavor', 'VykhinoZhulebino');
insert into users (name, email, password) values ('Morales', 'Morales@syntax.flavor', 'Morales');
insert into users (name, email, password) values ('Tanggu', 'Tanggu@syntax.flavor', 'Tanggu');
insert into users (name, email, password) values ('Darenzhuang', 'Darenzhuang@syntax.flavor', 'Darenzhuang');
insert into users (name, email, password) values ('San Lucas Sacatepéquez', 'SanLucasSacatepequez@syntax.flavor', 'SanLucasSacatepequez');
insert into users (name, email, password) values ('Norfolk County', 'NorfolkCounty@syntax.flavor', 'NorfolkCounty');
insert into users (name, email, password) values ('Wagini', 'Wagini@syntax.flavor', 'Wagini');
insert into users (name, email, password) values ('Chelgard', 'Chelgard@syntax.flavor', 'Chelgard');
insert into users (name, email, password) values ('Dalazi', 'Dalazi@syntax.flavor', 'Dalazi');
insert into users (name, email, password) values ('Meicheng', 'Meicheng@syntax.flavor', 'Meicheng');
insert into users (name, email, password) values ('Jeponkrajan', 'Jeponkrajan@syntax.flavor', 'Jeponkrajan');
insert into users (name, email, password) values ('Canutama', 'Canutama@syntax.flavor', 'Canutama');
insert into users (name, email, password) values ('Laojieji', 'Laojieji@syntax.flavor', 'Laojieji');
insert into users (name, email, password) values ('Gori', 'Gori@syntax.flavor', 'Gori');
insert into users (name, email, password) values ('Krasnaye', 'Krasnaye@syntax.flavor', 'Krasnaye');
insert into users (name, email, password) values ('Nong Yai', 'NongYai@syntax.flavor', 'NongYai');
insert into users (name, email, password) values ('Chambly', 'Chambly@syntax.flavor', 'Chambly');
insert into users (name, email, password) values ('Siruma', 'Siruma@syntax.flavor', 'Siruma');
insert into users (name, email, password) values ('Hejia', 'Hejia@syntax.flavor', 'Hejia');
insert into users (name, email, password) values ('Hongqi', 'Hongqi@syntax.flavor', 'Hongqi');
insert into users (name, email, password) values ('Ermelo', 'Ermelo@syntax.flavor', 'Ermelo');
insert into users (name, email, password) values ('Napanee Downtown', 'NapaneeDowntown@syntax.flavor', 'NapaneeDowntown');
insert into users (name, email, password) values ('Oemollo', 'Oemollo@syntax.flavor', 'Oemollo');
insert into users (name, email, password) values ('Rušanj', 'Rusan@syntax.flavor', 'Rusan');
insert into users (name, email, password) values ('Riyue', 'Riyue@syntax.flavor', 'Riyue');
insert into users (name, email, password) values ('Zeya', 'Zeya@syntax.flavor', 'Zeya');
insert into users (name, email, password) values ('Karangmelok', 'Karangmelok@syntax.flavor', 'Karangmelok');
insert into users (name, email, password) values ('Daqiao', 'Daqiao@syntax.flavor', 'Daqiao');
insert into users (name, email, password) values ('Cordeiro', 'Cordeiro@syntax.flavor', 'Cordeiro');
insert into users (name, email, password) values ('Mijiang', 'Mijiang@syntax.flavor', 'Mijiang');
insert into users (name, email, password) values ('Joconal', 'Joconal@syntax.flavor', 'Joconal');
insert into users (name, email, password) values ('Dongshan', 'Dongshan@syntax.flavor', 'Dongshan');
insert into users (name, email, password) values ('Pápa', 'Papa@syntax.flavor', 'Papa');
insert into users (name, email, password) values ('Corumbá', 'Corumba@syntax.flavor', 'Corumba');
insert into users (name, email, password) values ('Verkhozim', 'Verkhozim@syntax.flavor', 'Verkhozim');
insert into users (name, email, password) values ('Ibaraki', 'Ibaraki@syntax.flavor', 'Ibaraki');
insert into users (name, email, password) values ('Pingwang', 'Pingwang@syntax.flavor', 'Pingwang');
insert into users (name, email, password) values ('Mora', 'Mora@syntax.flavor', 'Mora');
insert into users (name, email, password) values ('Askainen', 'Askainen@syntax.flavor', 'Askainen');
insert into users (name, email, password) values ('Jāti', 'Jati@syntax.flavor', 'Jati');
insert into users (name, email, password) values ('Inderka', 'Inderka@syntax.flavor', 'Inderka');
insert into users (name, email, password) values ('Крушево', 'Krushevo@syntax.flavor', 'Krushevo');
insert into users (name, email, password) values ('Mangge', 'Mangge@syntax.flavor', 'Mangge');
insert into users (name, email, password) values ('Ubatuba', 'Ubatuba@syntax.flavor', 'Ubatuba');
insert into users (name, email, password) values ('Altunemil', 'Altunemil@syntax.flavor', 'Altunemil');
insert into users (name, email, password) values ('Altay', 'Altay@syntax.flavor', 'Altay');
insert into users (name, email, password) values ('Yandev', 'Yandev@syntax.flavor', 'Yandev');
insert into users (name, email, password) values ('Dingzigu', 'Dingzigu@syntax.flavor', 'Dingzigu');
insert into users (name, email, password) values ('Doghs', 'Doghs@syntax.flavor', 'Doghs');
insert into users (name, email, password) values ('Divisoria', 'Divisoria@syntax.flavor', 'Divisoria');
insert into users (name, email, password) values ('Tayabo', 'Tayabo@syntax.flavor', 'Tayabo');
insert into users (name, email, password) values ('Calangain', 'Calangain@syntax.flavor', 'Calangain');
insert into users (name, email, password) values ('Rio das Ostras', 'RiodasOstras@syntax.flavor', 'RiodasOstras');
insert into users (name, email, password) values ('Ouro Preto', 'OuroPreto@syntax.flavor', 'OuroPreto');
insert into users (name, email, password) values ('Ning’er', 'Ninger@syntax.flavor', 'Ninger');
insert into users (name, email, password) values ('Brodnica', 'Brodnica@syntax.flavor', 'Brodnica');
insert into users (name, email, password) values ('Châlons-en-Champagne', 'ChalonsenChampagne@syntax.flavor', 'ChalonsenChampagne');
insert into users (name, email, password) values ('Zhishan', 'Zhishan@syntax.flavor', 'Zhishan');
insert into users (name, email, password) values ('Vũ Thư', 'VuThu@syntax.flavor', 'VuThu');
insert into users (name, email, password) values ('Taoyao', 'Taoyao@syntax.flavor', 'Taoyao');
insert into users (name, email, password) values ('Gaokan', 'Gaokan@syntax.flavor', 'Gaokan');
insert into users (name, email, password) values ('Tucson', 'Tucson@syntax.flavor', 'Tucson');
insert into users (name, email, password) values ('Voiron', 'Voiron@syntax.flavor', 'Voiron');
insert into users (name, email, password) values ('Tangwang', 'Tangwang@syntax.flavor', 'Tangwang');
insert into users (name, email, password) values ('Dobri Dol', 'DobriDol@syntax.flavor', 'DobriDol');
insert into users (name, email, password) values ('Monguno', 'Monguno@syntax.flavor', 'Monguno');
insert into users (name, email, password) values ('Soito', 'Soito@syntax.flavor', 'Soito');
insert into users (name, email, password) values ('Pindi Bhattiān', 'PindiBhattian@syntax.flavor', 'PindiBhattian');
insert into users (name, email, password) values ('Kishi', 'Kishi@syntax.flavor', 'Kishi');
insert into users (name, email, password) values ('Gorno-Altaysk', 'GornoAltaysk@syntax.flavor', 'GornoAltaysk');
insert into users (name, email, password) values ('Sūrān', 'Suran@syntax.flavor', 'Suran');
insert into users (name, email, password) values ('San Juan', 'SanJuan@syntax.flavor', 'SanJuan');
insert into users (name, email, password) values ('Baláo', 'Balao@syntax.flavor', 'Balao');
insert into users (name, email, password) values ('Little Current', 'LittleCurrent@syntax.flavor', 'LittleCurrent');
insert into users (name, email, password) values ('Arias', 'Arias@syntax.flavor', 'Arias');
insert into users (name, email, password) values ('Las Vegas', 'LasVegas@syntax.flavor', 'LasVegas');
insert into users (name, email, password) values ('Jiaodai', 'Jiaodai@syntax.flavor', 'Jiaodai');
insert into users (name, email, password) values ('Xinbao', 'Xinbao@syntax.flavor', 'Xinbao');
insert into users (name, email, password) values ('Vancouver', 'Vancouver@syntax.flavor', 'Vancouver');
insert into users (name, email, password) values ('Tangnanzhen', 'Tangnanzhen@syntax.flavor', 'Tangnanzhen');
insert into users (name, email, password) values ('Al ‘Awjā', 'AlAwja@syntax.flavor', 'AlAwja');
