insert into menu_items (description, name, price) values ('Deliciosos triángulos de arroz rellenos de atún fresco, sazonados con un toque de salsa de soya y envueltos en una capa de alga nori crujiente.', 'Onigiris de Atún', 25.00);
insert into menu_items (description, name, price) values ('Un postre delicioso y fresco, perfecto para cualquier ocasión.', 'Cheesecake de Uvas', 30.00);
insert into menu_items (description, name, price) values ('Tacos de pollo con guacamole y salsa de chipotle.', 'Tacos de Pollo', 40.00);
insert into menu_items (description, name, price) values ('Pizza de pepperoni con queso mozzarella y salsa de tomate.', 'Pizza de Pepperoni', 50.00);
insert into menu_items (description, name, price) values ('Hamburguesa con carne de res, lechuga, tomate, cebolla y queso cheddar.', 'Hamburguesa Clásica', 35.00);
insert into menu_items (description, name, price) values ('Té helado de limón, perfecto para refrescarte en un día caluroso.', 'Té Helado', 15.00);
insert into menu_items (description, name, price) values ('Un pastel de chocolate esponjoso y delicioso, perfecto para los amantes del chocolate.', 'Pastel de Chocolate', 30.00);
insert into menu_items (description, name, price) values ('Rollitos de primavera rellenos de vegetales frescos y acompañados de salsa agridulce.', 'Rollitos de Primavera', 20.00);
insert into menu_items (description, name, price) values ('Copa de helado de vainilla con nueces y chocolate caliente.', 'Sundae de Vainilla', 18.00);
insert into menu_items (description, name, price) values ('Sándwich de jamón serrano con queso brie y rúcula en pan de centeno.', 'Sándwich Serrano', 45.00);
insert into menu_items (description, name, price) values ('Ensalada de quinoa con aguacate, tomate, y aderezo de limón.', 'Ensalada de Quinoa', 28.00);
insert into menu_items (description, name, price) values ('Paella de mariscos con mejillones, camarones y calamares.', 'Paella de Mariscos', 60.00);
insert into menu_items (description, name, price) values ('Tazón de acai con frutas frescas, granola, y miel.', 'Tazón de Acai', 35.00);
insert into menu_items (description, name, price) values ('Pasta al pesto con queso parmesano y piñones.', 'Pasta al Pesto', 48.00);
insert into menu_items (description, name, price) values ('Lasaña de carne con capas de pasta, salsa de tomate y queso mozzarella.', 'Lasaña de Carne', 50.00);
insert into menu_items (description, name, price) values ('Empanadas de queso con masa crujiente y relleno cremoso.', 'Empanadas de Queso', 15.00);
insert into menu_items (description, name, price) values ('Salteado de vegetales con tofu y salsa teriyaki.', 'Salteado de Tofu', 32.00);
insert into menu_items (description, name, price) values ('Fajitas de res con pimientos y cebolla, acompañadas de tortillas.', 'Fajitas de Res', 42.00);
insert into menu_items (description, name, price) values ('Brownie de chocolate con nueces y helado de vainilla.', 'Brownie de Chocolate', 22.00);
insert into menu_items (description, name, price) values ('Churros crujientes con azúcar y canela, servidos con salsa de chocolate.', 'Churros con Chocolate', 18.00);
insert into menu_items (description, name, price) values ('Ceviche de camarones con jugo de limón, cebolla y cilantro.', 'Ceviche de Camarones', 38.00);
insert into menu_items (description, name, price) values ('Batido de frutas tropicales con leche de coco.', 'Batido Tropical', 16.00);
insert into menu_items (description, name, price) values ('Café americano acompañado de galletas de mantequilla.', 'Café Americano', 10.00);
insert into menu_items (description, name, price) values ('Sopa miso con tofu, algas, y cebolla verde.', 'Sopa Miso', 12.00);
insert into menu_items (description, name, price) values ('Sushi de salmón con aguacate y arroz.', 'Sushi de Salmón', 28.00);
insert into menu_items (description, name, price) values ('Papas fritas con queso cheddar y trozos de tocino.', 'Papas Fritas con Queso', 25.00);
insert into menu_items (description, name, price) values ('Croissant de mantequilla recién horneado.', 'Croissant', 12.00);
insert into menu_items (description, name, price) values ('Té verde con limón y miel, perfecto para relajarse.', 'Té Verde', 8.00);
insert into menu_items (description, name, price) values ('Tortilla española con papas y cebolla.', 'Tortilla Española', 24.00);
insert into menu_items (description, name, price) values ('Bagel con salmón ahumado, queso crema y alcaparras.', 'Bagel de Salmón', 30.00);
insert into menu_items (description, name, price) values ('Crema de champiñones con croutones y perejil.', 'Sopa de Champiñones', 22.00);
insert into menu_items (description, name, price) values ('Jugo natural de naranja recién exprimido.', 'Jugo de Naranja', 12.00);
insert into menu_items (description, name, price) values ('Pizza margarita con tomate fresco, albahaca y mozzarella.', 'Pizza Margarita', 48.00);
insert into menu_items (description, name, price) values ('Helado de chocolate artesanal con virutas de cacao.', 'Helado de Chocolate', 18.00);
insert into menu_items (description, name, price) values ('Canelones rellenos de ricotta y espinacas, gratinados con queso.', 'Canelones de Espinaca', 45.00);
insert into menu_items (description, name, price) values ('Burrito de carne de res con frijoles, arroz y salsa.', 'Burrito de Res', 35.00);
insert into menu_items (description, name, price) values ('Pollo a la parrilla con ensalada de papas y verduras asadas.', 'Pollo a la Parrilla', 42.00);
insert into menu_items (description, name, price) values ('Crema catalana tradicional con una capa crujiente de azúcar caramelizado.', 'Crema Catalana', 28.00);
insert into menu_items (description, name, price) values ('Pancakes esponjosos servidos con frutas frescas y miel.', 'Pancakes con Frutas', 22.00);
insert into menu_items (description, name, price) values ('Ensalada caprese con tomates frescos, mozzarella y albahaca.', 'Ensalada Caprese', 25.00);
insert into menu_items (description, name, price) values ('Gazpacho frío de tomate y pepino, ideal para los días calurosos.', 'Gazpacho', 18.00);
insert into menu_items (description, name, price) values ('Sándwich de pollo con lechuga, tomate, y mayonesa en pan integral.', 'Sándwich de Pollo', 30.00);
insert into menu_items (description, name, price) values ('Nachos con queso fundido, guacamole, y pico de gallo.', 'Nachos con Queso', 20.00);
insert into menu_items (description, name, price) values ('Café cappuccino con espuma de leche y un toque de canela.', 'Cappuccino', 12.00);
insert into menu_items (description, name, price) values ('Sopa de lentejas con zanahorias y patatas.', 'Sopa de Lentejas', 22.00);
insert into menu_items (description, name, price) values ('Tostadas francesas con jarabe de arce y mantequilla.', 'Tostadas Francesas', 18.00);
insert into menu_items (description, name, price) values ('Ensalada César con pollo a la parrilla, croutones, y aderezo César.', 'Ensalada César', 26.00);
insert into menu_items (description, name, price) values ('Brochetas de camarones a la parrilla con limón y ajo.', 'Brochetas de Camarón', 40.00);
insert into menu_items (description, name, price) values ('Croquetas de jamón crujientes por fuera y cremosas por dentro.', 'Croquetas de Jamón', 18.00);
insert into menu_items (description, name, price) values ('Helado de fresa con trozos de fresas frescas.', 'Helado de Fresa', 15.00);