name: Build and Push Static Services to ECR

on:
  push:
    branches:
      - main
      - OscarCB
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest

jobs:
  build_and_push_syntaxflavor_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for syntaxflavor_db
        run: |
          docker build -f Dockerfile.postgres -t ${{ secrets.ECR_URI_SYNTAXFLAVOR_DB }}:${{ env.IMAGE_TAG }} .

      - name: Push syntaxflavor_db to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_URI_SYNTAXFLAVOR_DB }}:${{ env.IMAGE_TAG }}

  build_and_push_syntaxflavor_keycloak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for syntaxflavor_keycloak
        run: |
          docker build -f Dockerfile.keycloak -t ${{ secrets.ECR_URI_SYNTAXFLAVOR_KEYCLOAK }}:${{ env.IMAGE_TAG }} .

      - name: Push syntaxflavor_keycloak to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_URI_SYNTAXFLAVOR_KEYCLOAK }}:${{ env.IMAGE_TAG }}

  build_and_push_mailhog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for syntaxflavor_keycloak
        run: |
          docker build -f Dockerfile.mailhog -t ${{ secrets.ECR_URI_MAILHOG }}:${{ env.IMAGE_TAG }} .

      - name: Push syntaxflavor_keycloak to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_URI_MAILHOG }}:${{ env.IMAGE_TAG }}

  build_and_push_syntaxflavor_minio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for syntaxflavor_keycloak
        run: |
          docker build -f Dockerfile.minio -t ${{ secrets.ECR_URI_MINIO }}:${{ env.IMAGE_TAG }} .

      - name: Push syntaxflavor_keycloak to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_URI_MINIO }}:${{ env.IMAGE_TAG }}